=== deAssisF/pos-2025-tarefas/xsd/cardapio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:c="http://cardapio.org" targetNamespace="http://cardapio.org" elementFormDefault="qualified">
    <element name="cardapio">
        <complexType>
            <sequence>
                <element ref="c:prato" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="prato">
        <complexType>
            <sequence>
                <element ref="c:nome"/>
                <element ref="c:descricao"/>
                <element ref="c:ingredientes"/>
                <element ref="c:preco"/>
                <element ref="c:calorias"/>
                <element ref="c:tempoPreparo"/>
            </sequence>
            <attribute name="id" type="integer" use="required"/>
        </complexType>
    </element>
    <element name="nome" type="string"/>
    <element name="descricao" type="string"/>
    <element name="ingredientes">
        <complexType>
            <sequence>
                <element ref="c:ingrediente" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="ingrediente" type="string"/>
    <element name="preco">
        <complexType>
            <sequence>
                <element name="moeda" type="string"/>
                <element name="valor" type="decimal"/>
            </sequence>
        </complexType>
    </element>
    <element name="calorias" type="integer"/>
    <element name="tempoPreparo" type="string"/>
</schema>

=== deAssisF/pos-2025-tarefas/xsd/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<cardapio xmlns="cardapio.xml"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="cardapio.xml cardapio.xsd">
    <prato id="1">
        <nome>Pão de Queijo Mineiro</nome>
        <descricao>Delicioso pão de queijo tradicional de Minas Gerais</descricao>
        <ingredientes>
            <ingrediente>Polvilho</ingrediente>
            <ingrediente>Queijo Minas</ingrediente>
            <ingrediente>Leite</ingrediente>
        </ingredientes>
        <preco>15.00</preco>
        <calorias>150</calorias>
        <tempoPreparo>20 minutos</tempoPreparo>
    </prato>
    <prato id="2">
        <nome>Feijoada Completa</nome>
        <descricao>Prato tradicional brasileiro com feijão preto e variedade de carnes</descricao>
        <ingredientes>
            <ingrediente>Feijão preto</ingrediente>
            <ingrediente>Linguiça</ingrediente>
            <ingrediente>Costela</ingrediente>
            <ingrediente>Couve</ingrediente>
        </ingredientes>
        <preco>45.00</preco>
        <calorias>850</calorias>
        <tempoPreparo>240 minutos</tempoPreparo>
    </prato>
    <prato id="3">
        <nome>Brigadeiro Gourmet</nome>
        <descricao>Doce brasileiro com chocolate 70% e granulado especial</descricao>
        <ingredientes>
            <ingrediente>Chocolate amargo</ingrediente>
            <ingrediente>Leite condensado</ingrediente>
            <ingrediente>Manteiga</ingrediente>
        </ingredientes>
        <preco>8.00</preco>
        <calorias>120</calorias>
        <tempoPreparo>25 minutos</tempoPreparo>
    </prato>
</cardapio>
